Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.

Hints: Consider using the range(#begin, #end) method.

In [1]:
l1=[]
for x in range(2000,3201,1):
     if (x%7==0) and(x*5!=0): 
                print(x)
                l1.append(x)
l1

2002
2009
2016
2023
2030
2037
2044
2051
2058
2065
2072
2079
2086
2093
2100
2107
2114
2121
2128
2135
2142
2149
2156
2163
2170
2177
2184
2191
2198
2205
2212
2219
2226
2233
2240
2247
2254
2261
2268
2275
2282
2289
2296
2303
2310
2317
2324
2331
2338
2345
2352
2359
2366
2373
2380
2387
2394
2401
2408
2415
2422
2429
2436
2443
2450
2457
2464
2471
2478
2485
2492
2499
2506
2513
2520
2527
2534
2541
2548
2555
2562
2569
2576
2583
2590
2597
2604
2611
2618
2625
2632
2639
2646
2653
2660
2667
2674
2681
2688
2695
2702
2709
2716
2723
2730
2737
2744
2751
2758
2765
2772
2779
2786
2793
2800
2807
2814
2821
2828
2835
2842
2849
2856
2863
2870
2877
2884
2891
2898
2905
2912
2919
2926
2933
2940
2947
2954
2961
2968
2975
2982
2989
2996
3003
3010
3017
3024
3031
3038
3045
3052
3059
3066
3073
3080
3087
3094
3101
3108
3115
3122
3129
3136
3143
3150
3157
3164
3171
3178
3185
3192
3199

[2002,
 2009,
 2016,
 2023,
 2030,
 2037,
 2044,
 2051,
 2058,
 2065,
 2072,
 2079,
 2086,
 2093,
 2100,
 2107,
 2114,
 2121,
 2128,
 2135,
 2142,
 2149,
 2156,
 2163,
 2170,
 2177,
 2184,
 2191,
 2198,
 2205,
 2212,
 2219,
 2226,
 2233,
 2240,
 2247,
 2254,
 2261,
 2268,
 2275,
 2282,
 2289,
 2296,
 2303,
 2310,
 2317,
 2324,
 2331,
 2338,
 2345,
 2352,
 2359,
 2366,
 2373,
 2380,
 2387,
 2394,
 2401,
 2408,
 2415,
 2422,
 2429,
 2436,
 2443,
 2450,
 2457,
 2464,
 2471,
 2478,
 2485,
 2492,
 2499,
 2506,
 2513,
 2520,
 2527,
 2534,
 2541,
 2548,
 2555,
 2562,
 2569,
 2576,
 2583,
 2590,
 2597,
 2604,
 2611,
 2618,
 2625,
 2632,
 2639,
 2646,
 2653,
 2660,
 2667,
 2674,
 2681,
 2688,
 2695,
 2702,
 2709,
 2716,
 2723,
 2730,
 2737,
 2744,
 2751,
 2758,
 2765,
 2772,
 2779,
 2786,
 2793,
 2800,
 2807,
 2814,
 2821,
 2828,
 2835,
 2842,
 2849,
 2856,
 2863,
 2870,
 2877,
 2884,
 2891,
 2898,
 2905,
 2912,
 2919,
 2926,
 2933,
 2940,
 2947,
 2954,
 2961,
 2968,
 2975,
 2982,
 2989,
 2996,
 3003,
 3010,
 3017,
 3024,
 3031,
 3038,
 3045,
 3052,
 3059,
 3066,
 3073,
 3080,
 3087,
 3094,
 3101,
 3108,
 3115,
 3122,
 3129,
 3136,
 3143,
 3150,
 3157,
 3164,
 3171,
 3178,
 3185,
 3192,
 3199]

tive integers less than or equal to n). for example factorial(5)= 5 x Write a program that can compute the factorial of a given number. (the factorial of n is the product of all posi 4 x 3 x 2 x 1 the result is 120.  (i.e. factorial (0)=1)

In [2]:
def factorial(x):
    if x == 0:
        return 1
    else:
        return x * factorial(x-1)
x=int(input("Input a number to compute the factiorial : "))
print(factorial(x))

Input a number to compute the factiorial : 5
120

With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [3]:
number = int(input("Type a number: "))
numberDict = {}
for i in range(1, number+1):
    numberDict[i] = i*i
print(numberDict)

Type a number: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

Given a non-empty string and an int n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive). 

missing_char('kitten', 1) → 'ktten'    for example here we remove "i" which is located in the index 1

missing_char('kitten', 0) → 'itten'   here we remove "k" which is in the index 0

missing_char('kitten', 4) → 'kittn'   here we remove "e" which is in the index 4

In [4]:
def remove_char(str1, n):
      first_part = str1[:n] 
      last_part = str1[n+1:]
      return first_part + last_part
print(remove_char('kitten', 1))
print(remove_char('kitten', 0))
print(remove_char('kitten', 4))

ktten
itten
kittn

Write a NumPy program to convert a NumPy array into a Python list structure.

Expected Output: 

Original array elements: [[0 1] [2 3] [4 5]] 

Array to list: [[0, 1], [2, 3], [4, 5]] 
 

Hint: we can use the to_list() function to ensure the conversion.

In [5]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

Write a NumPy program to compute the covariance matrix of two given arrays. 

Original array1: [0 1 2] 

Original array2: [2 1 0] 

Covariance matrix of the said arrays: [[ 1. -1.] [-1. 1.]]
 

Hint: We can use the np.cov() function to calculate the covariance between these two arrays

In [6]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print ("original array 1:")
print (x)
print("orginal array 2:")
print(y)
print("Covariance matrix of the said arrays", np.cov(x,y))

original array 1:
[0 1 2]
orginal array 2:
[2 1 0]
Covariance matrix of the said arrays [[ 1. -1.]
 [-1.  1.]]

Question: Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

D is the variable whose values should be input into your program in a comma-separated sequence. (that means D contains more than value)

Example Let's assume the following comma-separated input sequence is given to the program: 100,150,180 The output of the program should be: 18,22,24 

To further explain this, we will obtain a result for each value of D:  Q1= Square root of [(2 * C * 100)/H] =18, Q2= Square root of [(2 * C * 150)/H] = 22 and Q3 = Square root of [(2 * C * 180)/H]  = 24

Hints: If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26) In case of input data being supplied to the question, it should be assumed to be a console input.

In [19]:

D = int(input(input number:))
C=50
H=30
Q= [(2 * C * D)/H]**
             
print(Q)

SyntaxError: invalid syntax (<ipython-input-19-899067f59554>, line 1)